# Site settings
author: Mars Le
title: Software from Mars 
header-img: img/home-bg.png
email: hp.mars.le@gmail.com
copyright_name: Mars Le
description: > # this means to ignore newlines until "baseurl:"
  Journey to software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hpmarsle

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
